global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "exporter"
    static_configs:
      - targets: ["exporter:8000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]